[package]
name = "prefix-expr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
rstest = "0.12.0"
gramma-rs = { path = "../../gramma-rs" }
