[package]
name = "small-regex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphviz-rust = "0.1.2"
gramma-rs = { path = "../../gramma-rs" }